import "./globals.css";


export const metadata = {
  title: "Bikkey Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          {metadata.title}
        </title>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/69/69840.png" />
      </head>
      <body className="">{children}</body>
    </html>
  );
}
